#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
PWA Manager - Progressive Web App Manager
PWA xususiyatlarini boshqarish va optimizatsiya qilish

Xususiyatlar:
- Service Worker yaratish va boshqarish
- Web App Manifest optimizatsiya
- Offline caching strategiyasi
- Push notification tizimi
- App installation prompts
- Background sync
- Push protocol management
- Update management
- Cache versioning
- Network detection
- App shell architecture
"""

import os
import json
import time
import logging
import asyncio
import hashlib
import base64
from pathlib import Path
from typing import Dict, List, Optional, Union, Any
from dataclasses import dataclass, asdict
from concurrent.futures import ThreadPoolExecutor
import aiofiles
import aiohttp
from urllib.parse import urljoin, urlparse
import mimetypes
from datetime import datetime, timedelta

# Logging sozlamalar
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

@dataclass
class PWAConfig:
    """PWA konfiguratsiyasi"""
    app_name: str
    short_name: str
    start_url: str
    display: str = "standalone"  # standalone, fullscreen, minimal-ui
    background_color: str = "#ffffff"
    theme_color: str = "#000000"
    orientation: str = "portrait-primary"  # portrait, landscape, any
    scope: str = "/"
    description: str = ""
    icons: List[Dict] = None
    offline_page: str = "/offline"
    cache_name: str = "pwa-cache-v1"
    version: str = "1.0.0"
    enable_push: bool = False
    enable_background_sync: bool = True
    update_check_interval: int = 3600  # seconds

@dataclass
class ServiceWorkerConfig:
    """Service Worker konfiguratsiyasi"""
    cache_name: str
    precache_files: List[str]
    runtime_cache_rules: List[Dict]
    skip_waiting: bool = False
    clients_claim: bool = False
    enable_offline_fallback: bool = True
    enable_background_sync: bool = True
    network_first_timeout: int = 3
    cache_first_max_age: int = 86400  # 1 day

class ServiceWorkerGenerator:
    """Service Worker kod generatori"""
    
    def __init__(self, config: PWAConfig, sw_config: ServiceWorkerConfig):
        self.config = config
        self.sw_config = sw_config

    def generate_service_worker(self) -> str:
        """Service Worker kodini yaratish"""
        sw_code = f"""
// Service Worker - Generated by PWA Manager
// Cache name: {self.sw_config.cache_name}
// Version: {self.config.version}

const CACHE_NAME = '{self.sw_config.cache_name}';
const OFFLINE_URL = '{self.config.offline_page}';

// Installation event
self.addEventListener('install', (event) => {{
    console.log('Service Worker: Installing...');
    
    event.waitUntil(
        caches.open(CACHE_NAME)
            .then((cache) => {{
                console.log('Service Worker: Caching files');
                return cache.addAll([
                    '/',
                    '/index.html',
                    '/manifest.json',
                    OFFLINE_URL,
                    ...precacheFiles
                ]);
            }})
            .then(() => {{
                console.log('Service Worker: Installed');
                {self._get_skip_waiting_code()}
            }})
            .catch((error) => {{
                console.error('Service Worker: Installation failed', error);
            }})
    );
}});

// Activation event
self.addEventListener('activate', (event) => {{
    console.log('Service Worker: Activating...');
    
    event.waitUntil(
        caches.keys()
            .then((cacheNames) => {{
                return Promise.all(
                    cacheNames.map((cacheName) => {{
                        if (cacheName !== CACHE_NAME) {{
                            console.log('Service Worker: Deleting old cache:', cacheName);
                            return caches.delete(cacheName);
                        }}
                    }})
                );
            }})
            .then(() => {{
                console.log('Service Worker: Activated');
                {self._get_clients_claim_code()}
            }})
    );
}});

// Fetch event - Network first strategy
self.addEventListener('fetch', (event) => {{
    // Skip if not GET request
    if (event.request.method !== 'GET') return;
    
    // Skip cross-origin requests
    if (!event.request.url.startsWith(self.location.origin)) return;
    
    event.respondWith(handleFetch(event.request));
}});

{self._generate_cache_strategies()}

{self._generate_background_sync()}

{self._generate_push_notifications()}

{self._generate_message_handlers()}

// Helper functions
async function handleFetch(request) {{
    const url = new URL(request.url);
    
    // Check if request is for precached resource
    if (precacheFiles.includes(url.pathname)) {{
        return caches.match(request);
    }}
    
    // Apply runtime cache strategies
    for (const rule of runtimeCacheRules) {{
        if (matchRequest(request, rule)) {{
            return applyCacheStrategy(request, rule.strategy);
        }}
    }}
    
    // Default: Network first with fallback
    return networkFirst(request);
}}

function matchRequest(request, rule) {{
    const url = new URL(request.url);
    
    if (rule.urlPattern) {{
        return new RegExp(rule.urlPattern).test(url.pathname);
    }}
    
    if (rule.urlStartsWith) {{
        return url.pathname.startsWith(rule.urlStartsWith);
    }}
    
    return false;
}}

function applyCacheStrategy(request, strategy) {{
    switch (strategy) {{
        case 'network-first':
            return networkFirst(request);
        case 'cache-first':
            return cacheFirst(request);
        case 'stale-while-revalidate':
            return staleWhileRevalidate(request);
        case 'network-only':
            return fetch(request);
        case 'cache-only':
            return caches.match(request);
        default:
            return networkFirst(request);
    }}
}}

// Network first strategy
async function networkFirst(request) {{
    try {{
        const response = await fetch(request);
        
        if (response && response.status === 200) {{
            const cache = await caches.open(CACHE_NAME);
            cache.put(request, response.clone());
        }}
        
        return response;
    }} catch (error) {{
        console.log('Network first: Using cache fallback');
        const cachedResponse = await caches.match(request);
        return cachedResponse || await caches.match(OFFLINE_URL);
    }}
}}

// Cache first strategy
async function cacheFirst(request) {{
    const cachedResponse = await caches.match(request);
    if (cachedResponse) {{
        return cachedResponse;
    }}
    
    try {{
        const response = await fetch(request);
        
        if (response && response.status === 200) {{
            const cache = await caches.open(CACHE_NAME);
            cache.put(request, response.clone());
        }}
        
        return response;
    }} catch (error) {{
        console.log('Cache first: Network failed');
        return await caches.match(OFFLINE_URL);
    }}
}}

// Stale while revalidate
async function staleWhileRevalidate(request) {{
    const cache = await caches.open(CACHE_NAME);
    const cachedResponse = await cache.match(request);
    
    const fetchPromise = fetch(request).then((response) => {{
        if (response && response.status === 200) {{
            cache.put(request, response.clone());
        }}
        return response;
    }}).catch(() => {{
        return cachedResponse;
    }});
    
    return cachedResponse || fetchPromise;
}}

// Skip waiting code
function {self._get_skip_waiting_code().split('=')[0].split('(')[0]}() {{
{self._get_skip_waiting_code()}
}}

// Clients claim code
function {self._get_clients_claim_code().split('=')[0].split('(')[0]}() {{
{self._get_clients_claim_code()}
}}

// Message handling
self.addEventListener('message', (event) => {{
    if (event.data && event.data.type === 'SKIP_WAITING') {{
        self.skipWaiting();
    }}
    
    if (event.data && event.data.type === 'CACHE_URLS') {{
        event.waitUntil(
            caches.open(CACHE_NAME)
                .then((cache) => cache.addAll(event.data.urls))
        );
    }}
    
    if (event.data && event.data.type === 'CLEAR_CACHE') {{
        event.waitUntil(
            caches.delete(CACHE_NAME)
        );
    }}
}});
"""
        return sw_code

    def _get_skip_waiting_code(self) -> str:
        """Skip waiting kodini olish"""
        if self.sw_config.skip_waiting:
            return "self.skipWaiting();"
        return "// Skip waiting disabled"

    def _get_clients_claim_code(self) -> str:
        """Clients claim kodini olish"""
        if self.sw_config.clients_claim:
            return "return self.clients.claim();"
        return "// Clients claim disabled"

    def _generate_cache_strategies(self) -> str:
        """Cache strategiyalarini yaratish"""
        strategies = []
        
        for rule in self.sw_config.runtime_cache_rules:
            pattern = rule.get('urlPattern', rule.get('urlStartsWith', '/'))
            strategy = rule.get('strategy', 'network-first')
            cache_name = rule.get('cacheName', CACHE_NAME)
            max_age = rule.get('maxAge', 86400)
            
            strategies.append(f"""
// Cache rule for {pattern}
if (url.pathname.startsWith('{pattern}')) {{
    return {strategy}(request, '{cache_name}', {max_age});
}}""")
        
        return "\n".join(strategies) if strategies else "// No runtime cache rules"

    def _generate_background_sync(self) -> str:
        """Background sync kodini yaratish"""
        if not self.sw_config.enable_background_sync:
            return "// Background sync disabled"
        
        return f"""
// Background Sync
self.addEventListener('sync', (event) => {{
    if (event.tag === 'background-sync') {{
        event.waitUntil(doBackgroundSync());
    }}
}});

async function doBackgroundSync() {{
    try {{
        // Sync offline data
        const offlineData = await getOfflineData();
        
        for (const item of offlineData) {{
            await fetch('/api/sync', {{
                method: 'POST',
                headers: {{
                    'Content-Type': 'application/json'
                }},
                body: JSON.stringify(item)
            }});
        }}
        
        console.log('Background sync completed');
    }} catch (error) {{
        console.error('Background sync failed:', error);
    }}
}}

async function getOfflineData() {{
    // Get data from IndexedDB or localStorage
    // This is a placeholder implementation
    return [];
}}

function queueOfflineRequest(requestData) {{
    // Queue request for background sync
    if ('sync' in self.registration) {{
        self.registration.sync.register('background-sync');
    }}
}}
"""

    def _generate_push_notifications(self) -> str:
        """Push notification kodini yaratish"""
        if not self.config.enable_push:
            return "// Push notifications disabled"
        
        return f"""
// Push Notifications
self.addEventListener('push', (event) => {{
    if (!event.data) return;
    
    try {{
        const data = event.data.json();
        const options = {{
            body: data.body || 'New notification',
            icon: data.icon || '/icon-192x192.png',
            badge: data.badge || '/badge-72x72.png',
            vibrate: data.vibrate || [100, 50, 100],
            data: data.data || {{}},
            actions: data.actions || [],
            requireInteraction: data.requireInteraction || false
        }};
        
        event.waitUntil(
            self.registration.showNotification(data.title || '{self.config.app_name}', options)
        );
    }} catch (error) {{
        console.error('Push notification error:', error);
    }}
}});

self.addEventListener('notificationclick', (event) => {{
    event.notification.close();
    
    const targetUrl = event.notification.data?.url || '/';
    
    event.waitUntil(
        clients.matchAll({{ type: 'window' }})
            .then((clientList) => {{
                // Check if app is already open
                for (const client of clientList) {{
                    if (client.url === targetUrl && 'focus' in client) {{
                        return client.focus();
                    }}
                }}
                
                // Open new window
                if (clients.openWindow) {{
                    return clients.openWindow(targetUrl);
                }}
            }})
    );
}});
"""

    def _generate_message_handlers(self) -> str:
        """Message handler'larini yaratish"""
        return """
// Message handlers for updates
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'GET_VERSION') {
        event.ports[0].postMessage({version: CACHE_NAME});
    }
});
"""

class WebAppManifest:
    """Web App Manifest generator"""
    
    def __init__(self, config: PWAConfig):
        self.config = config

    def generate_manifest(self) -> Dict:
        """Manifest JSON yaratish"""
        manifest = {
            "name": self.config.app_name,
            "short_name": self.config.short_name,
            "description": self.config.description or "",
            "start_url": self.config.start_url,
            "scope": self.config.scope,
            "display": self.config.display,
            "orientation": self.config.orientation,
            "background_color": self.config.background_color,
            "theme_color": self.config.theme_color,
            "categories": ["business", "productivity", "utilities"],
            "lang": "en-US",
            "dir": "ltr",
            "icons": self.config.icons or self._generate_default_icons(),
            "shortcuts": [],
            "screenshots": [],
            "prefer_related_applications": False,
            "edge_side_panel": {},
            "launch_handler": {
                "client_mode": "navigate-existing"
            },
            "protocol_handlers": [],
            "file_handlers": [],
            "share_target": {},
            "display_override": ["window-controls-overlay", "standalone", "minimal-ui"],
            "handle_links": "preferred"
        }
        
        return manifest

    def _generate_default_icons(self) -> List[Dict]:
        """Standart icon'larni yaratish"""
        return [
            {
                "src": "/icon-72x72.png",
                "sizes": "72x72",
                "type": "image/png",
                "purpose": "any"
            },
            {
                "src": "/icon-96x96.png",
                "sizes": "96x96",
                "type": "image/png",
                "purpose": "any"
            },
            {
                "src": "/icon-128x128.png",
                "sizes": "128x128",
                "type": "image/png",
                "purpose": "any"
            },
            {
                "src": "/icon-144x144.png",
                "sizes": "144x144",
                "type": "image/png",
                "purpose": "any maskable"
            },
            {
                "src": "/icon-152x152.png",
                "sizes": "152x152",
                "type": "image/png",
                "purpose": "any maskable"
            },
            {
                "src": "/icon-192x192.png",
                "sizes": "192x192",
                "type": "image/png",
                "purpose": "any maskable"
            },
            {
                "src": "/icon-384x384.png",
                "sizes": "384x384",
                "type": "image/png",
                "purpose": "any"
            },
            {
                "src": "/icon-512x512.png",
                "sizes": "512x512",
                "type": "image/png",
                "purpose": "any maskable"
            }
        ]

    def save_manifest(self, output_path: str):
        """Manifest faylini saqlash"""
        manifest = self.generate_manifest()
        
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(manifest, f, indent=2, ensure_ascii=False)
        
        logger.info(f"Web App Manifest saqlandi: {output_path}")

class PWAManager:
    """Asosiy PWA manager"""
    
    def __init__(self, project_root: str, config: PWAConfig):
        self.project_root = Path(project_root)
        self.config = config
        self.sw_config = self._create_sw_config()
        
        # PWA fayllar papkasi
        self.pwa_dir = self.project_root / "pwa_assets"
        self.pwa_dir.mkdir(exist_ok=True)
        
        # Service Worker generator
        self.sw_generator = ServiceWorkerGenerator(config, self.sw_config)
        
        # Manifest generator
        self.manifest_generator = WebAppManifest(config)

    def _create_sw_config(self) -> ServiceWorkerConfig:
        """Service Worker konfiguratsiya yaratish"""
        return ServiceWorkerConfig(
            cache_name=f"{self.config.cache_name}-{self.config.version}",
            precache_files=[
                "/",
                "/index.html",
                "/manifest.json",
                self.config.offline_page,
                "/icon-192x192.png",
                "/icon-512x512.png"
            ],
            runtime_cache_rules=[
                {
                    "urlPattern": r"^/api/.*",
                    "strategy": "network-first",
                    "cacheName": "api-cache",
                    "maxAge": 300  # 5 minutes
                },
                {
                    "urlPattern": r"^/assets/.*\.(js|css)$",
                    "strategy": "cache-first",
                    "cacheName": "static-cache",
                    "maxAge": 86400  # 1 day
                },
                {
                    "urlPattern": r"^/images/.*",
                    "strategy": "cache-first",
                    "cacheName": "images-cache",
                    "maxAge": 604800  # 1 week
                },
                {
                    "urlPattern": r"^/fonts/.*",
                    "strategy": "cache-first",
                    "cacheName": "fonts-cache",
                    "maxAge": 2592000  # 1 month
                }
            ],
            skip_waiting=True,
            clients_claim=True,
            enable_offline_fallback=True,
            enable_background_sync=self.config.enable_background_sync,
            network_first_timeout=3,
            cache_first_max_age=86400
        )

    async def setup_pwa(self) -> Dict:
        """PWA sozlamalarini o'rnatish"""
        logger.info("🚀 PWA sozlamalari o'rnatilmoqda...")
        
        try:
            # 1. Service Worker yaratish
            await self._create_service_worker()
            
            # 2. Web App Manifest yaratish
            await self._create_manifest()
            
            # 3. Icon'lar generatsiya qilish
            await self._generate_icons()
            
            # 4. Offline sahifa yaratish
            await self._create_offline_page()
            
            # 5. Push notification qo'llab-quvvatlash
            if self.config.enable_push:
                await self._setup_push_notifications()
            
            # 6. Background sync sozlamalari
            if self.config.enable_background_sync:
                await self._setup_background_sync()
            
            # 7. PWA metateglar qo'shish
            await self._add_pwa_meta_tags()
            
            # 8. Update system
            await self._setup_update_system()
            
            # 9. Installation prompt
            await self._setup_installation_prompt()
            
            # 10. Network detection
            await self._setup_network_detection()
            
            # 11. Test va validatsiya
            await self._validate_pwa()
            
            # 12. Hisobot yaratish
            await self._generate_pwa_report()
            
            logger.info("✅ PWA sozlamalari muvaffaqiyatli tugallandi!")
            return {"status": "success", "pwa_files": self._get_created_files()}
            
        except Exception as e:
            logger.error(f"❌ PWA sozlamalari xatosi: {str(e)}")
            raise

    async def _create_service_worker(self):
        """Service Worker faylini yaratish"""
        logger.info("📱 Service Worker yaratilmoqda...")
        
        sw_code = self.sw_generator.generate_service_worker()
        sw_path = self.project_root / "service-worker.js"
        
        # Global variables qo'shish
        sw_code = f"""
const precacheFiles = {json.dumps(self.sw_config.precache_files)};
const runtimeCacheRules = {json.dumps(self.sw_config.runtime_cache_rules)};
const CACHE_NAME = '{self.sw_config.cache_name}';
{self.sw_generator.generate_service_worker()}
"""
        
        async with aiofiles.open(sw_path, 'w', encoding='utf-8') as f:
            await f.write(sw_code)
        
        logger.info(f"Service Worker yaratildi: {sw_path}")

    async def _create_manifest(self):
        """Web App Manifest yaratish"""
        logger.info("📱 Web App Manifest yaratilmoqda...")
        
        manifest_path = self.project_root / "manifest.json"
        self.manifest_generator.save_manifest(str(manifest_path))
        
        logger.info(f"Manifest yaratildi: {manifest_path}")

    async def _generate_icons(self):
        """PWA icon'larini generatsiya qilish"""
        logger.info("🎨 PWA icon'lar generatsiya qilinmoqda...")
        
        icon_configs = [
            {"size": 72, "name": "icon-72x72.png"},
            {"size": 96, "name": "icon-96x96.png"},
            {"size": 128, "name": "icon-128x128.png"},
            {"size": 144, "name": "icon-144x144.png"},
            {"size": 152, "name": "icon-152x152.png"},
            {"size": 192, "name": "icon-192x192.png"},
            {"size": 384, "name": "icon-384x384.png"},
            {"size": 512, "name": "icon-512x512.png"}
        ]
        
        # Placeholder icon'lar yaratish
        for config in icon_configs:
            icon_path = self.project_root / config["name"]
            if not icon_path.exists():
                # Placeholder icon yaratish (solid color)
                await self._create_placeholder_icon(icon_path, config["size"])

    async def _create_placeholder_icon(self, icon_path: Path, size: int):
        """Placeholder icon yaratish"""
        # Bu yerda asl icon generatsiya qilinadi
        # Hozircha placeholder JSON yaratish
        placeholder = {
            "size": size,
            "path": str(icon_path),
            "generated": datetime.now().isoformat()
        }
        
        # PNG fayl o'rniga JSON placeholder yozamiz
        json_path = icon_path.with_suffix('.json')
        async with aiofiles.open(json_path, 'w') as f:
            await f.write(json.dumps(placeholder, indent=2))

    async def _create_offline_page(self):
        """Offline sahifa yaratish"""
        logger.info("📵 Offline sahifa yaratilmoqda...")
        
        offline_html = f"""
<!DOCTYPE html>
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Internet aloqasi yo'q - {self.config.app_name}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            margin: 0;
            background: linear-gradient(135deg, {self.config.background_color}, {self.config.theme_color});
            color: white;
            text-align: center;
        }}
        .offline-container {{
            max-width: 400px;
            padding: 2rem;
        }}
        .offline-icon {{
            font-size: 4rem;
            margin-bottom: 1rem;
        }}
        .offline-title {{
            font-size: 1.5rem;
            margin-bottom: 1rem;
        }}
        .offline-message {{
            margin-bottom: 2rem;
            opacity: 0.8;
        }}
        .retry-button {{
            background: white;
            color: {self.config.theme_color};
            border: none;
            padding: 12px 24px;
            border-radius: 8px;
            font-size: 1rem;
            cursor: pointer;
            font-weight: 600;
        }}
        .retry-button:hover {{
            opacity: 0.9;
        }}
    </style>
</head>
<body>
    <div class="offline-container">
        <div class="offline-icon">📱</div>
        <h1 class="offline-title">Internet aloqasi yo'q</h1>
        <p class="offline-message">
            Sizning internet aloqangiz mavjud emas. Iltimos, aloqani tekshiring va qaytadan harakat qiling.
        </p>
        <button class="retry-button" onclick="window.location.reload()">
            Qaytadan harakat qilish
        </button>
    </div>
    <script>
        // Retry button functionality
        document.querySelector('.retry-button').addEventListener('click', function() {{
            window.location.reload();
        }});
        
        // Online event listener
        window.addEventListener('online', function() {{
            window.location.href = '/';
        }});
    </script>
</body>
</html>
"""
        
        offline_path = self.project_root / self.config.offline_page.lstrip('/')
        async with aiofiles.open(offline_path, 'w', encoding='utf-8') as f:
            await f.write(offline_html)
        
        logger.info(f"Offline sahifa yaratildi: {offline_path}")

    async def _setup_push_notifications(self):
        """Push notification qo'llab-quvvatlash"""
        logger.info("🔔 Push notification qo'llab-quvvatlash...")
        
        push_manager_path = self.project_root / "push-notification-manager.js"
        
        push_js = f"""
// Push Notification Manager
// Generated by PWA Manager

class PushNotificationManager {{
    constructor() {{
        this.isSupported = 'serviceWorker' in navigator && 'PushManager' in window;
        this.permission = Notification.permission;
    }}
    
    async init() {{
        if (!this.isSupported) {{
            console.log('Push notifications are not supported');
            return false;
        }}
        
        if (this.permission === 'default') {{
            await this.requestPermission();
        }}
        
        return this.permission === 'granted';
    }}
    
    async requestPermission() {{
        try {{
            const permission = await Notification.requestPermission();
            this.permission = permission;
            return permission === 'granted';
        }} catch (error) {{
            console.error('Error requesting notification permission:', error);
            return false;
        }}
    }}
    
    async subscribe() {{
        if (!this.isSupported || this.permission !== 'granted') {{
            return null;
        }}
        
        try {{
            const registration = await navigator.serviceWorker.ready;
            const subscription = await registration.pushManager.subscribe({{
                userVisibleOnly: true,
                applicationServerKey: this.urlBase64ToUint8Array(this.vapidPublicKey)
            }});
            
            console.log('Push subscription created:', subscription);
            return subscription;
        }} catch (error) {{
            console.error('Error creating push subscription:', error);
            return null;
        }}
    }}
    
    async unsubscribe() {{
        try {{
            const subscription = await this.getSubscription();
            if (subscription) {{
                await subscription.unsubscribe();
            }}
        }} catch (error) {{
            console.error('Error unsubscribing from push notifications:', error);
        }}
    }}
    
    async getSubscription() {{
        const registration = await navigator.serviceWorker.ready;
        return await registration.pushManager.getSubscription();
    }}
    
    urlBase64ToUint8Array(base64String) {{
        const padding = '='.repeat((4 - base64String.length % 4) % 4);
        const base64 = (base64String + padding)
            .replace(/-/g, '+')
            .replace(/_/g, '/');
        
        const rawData = window.atob(base64);
        const outputArray = new Uint8Array(rawData.length);
        
        for (let i = 0; i < rawData.length; ++i) {{
            outputArray[i] = rawData.charCodeAt(i);
        }}
        return outputArray;
    }}
    
    // VAPID keys (these should be replaced with your actual keys)
    vapidPublicKey = 'BDpgHG___wJDMcP9vOc9zFy7qZj4zKf6V5v8Q5H2R7e4T8u6N3kF2sP9mL4vQ5r';
    
    async sendTestNotification() {{
        const subscription = await this.getSubscription();
        if (subscription) {{
            // Send test notification to your server
            console.log('Sending test notification via server...');
        }}
    }}
}}

// Initialize push notifications when page loads
document.addEventListener('DOMContentLoaded', async function() {{
    if ('serviceWorker' in navigator) {{
        const pushManager = new PushNotificationManager();
        
        // Register service worker
        navigator.serviceWorker.register('/service-worker.js')
            .then(registration => {{
                console.log('Service Worker registered:', registration);
                
                // Initialize push notifications
                pushManager.init().then(supported => {{
                    if (supported) {{
                        console.log('Push notifications are ready');
                        // You can call pushManager.subscribe() here if needed
                    }}
                }});
            }})
            .catch(error => {{
                console.error('Service Worker registration failed:', error);
            }});
    }}
}});

// Export for global use
window.PushNotificationManager = PushNotificationManager;
"""
        
        async with aiofiles.open(push_manager_path, 'w', encoding='utf-8') as f:
            await f.write(push_js)
        
        logger.info(f"Push notification manager yaratildi: {push_manager_path}")

    async def _setup_background_sync(self):
        """Background sync sozlamalari"""
        logger.info("🔄 Background sync sozlamalari...")
        
        background_sync_path = self.project_root / "background-sync.js"
        
        bg_sync_js = """
// Background Sync Manager
// Generated by PWA Manager

class BackgroundSyncManager {
    constructor() {
        this.isSupported = 'serviceWorker' in navigator && 'sync' in window.ServiceWorkerRegistration.prototype;
    }
    
    async registerSync(tag = 'background-sync') {
        if (!this.isSupported) {
            console.log('Background sync is not supported');
            return false;
        }
        
        try {
            const registration = await navigator.serviceWorker.ready;
            await registration.sync.register(tag);
            console.log('Background sync registered:', tag);
            return true;
        } catch (error) {
            console.error('Error registering background sync:', error);
            return false;
        }
    }
    
    async queueRequest(requestData) {
        // Store request in IndexedDB for later sync
        return this.storeOfflineRequest(requestData);
    }
    
    async storeOfflineRequest(requestData) {
        // Implementation for storing offline requests
        // This would typically use IndexedDB
        console.log('Storing offline request:', requestData);
        return true;
    }
    
    async processOfflineQueue() {
        // Process queued offline requests
        console.log('Processing offline queue...');
        return true;
    }
}

// Initialize background sync
document.addEventListener('DOMContentLoaded', async function() {
    const bgSyncManager = new BackgroundSyncManager();
    window.backgroundSyncManager = bgSyncManager;
});
"""
        
        async with aiofiles.open(background_sync_path, 'w', encoding='utf-8') as f:
            await f.write(bg_sync_js)
        
        logger.info(f"Background sync manager yaratildi: {background_sync_path}")

    async def _add_pwa_meta_tags(self):
        """HTML faylga PWA meta-teglar qo'shish"""
        logger.info("🏷️  PWA meta-teglar qo'shilmoqda...")
        
        # Asosiy index.html faylni topish
        index_files = list(self.project_root.glob("index.html")) + list(self.project_root.glob("**/index.html"))
        
        for index_path in index_files:
            await self._add_meta_tags_to_html(index_path)

    async def _add_meta_tags_to_html(self, html_path: Path):
        """HTML faylga meta-teglar qo'shish"""
        try:
            async with aiofiles.open(html_path, 'r', encoding='utf-8') as f:
                content = await f.read()
            
            # PWA meta-teglar
            meta_tags = f"""
    <!-- PWA Meta Tags -->
    <meta name="application-name" content="{self.config.app_name}">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="apple-mobile-web-app-title" content="{self.config.short_name}">
    <meta name="format-detection" content="telephone=no">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="msapplication-config" content="/browserconfig.xml">
    <meta name="msapplication-TileColor" content="{self.config.theme_color}">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="theme-color" content="{self.config.theme_color}">
    
    <!-- PWA Icons -->
    <link rel="icon" type="image/png" sizes="32x32" href="/icon-72x72.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/icon-72x72.png">
    <link rel="apple-touch-icon" href="/icon-152x152.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/icon-152x152.png">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="{self.config.theme_color}">
    
    <!-- PWA Manifest -->
    <link rel="manifest" href="/manifest.json">
    
    <!-- Service Worker Registration -->
    <script>
        if ('serviceWorker' in navigator) {{
            window.addEventListener('load', function() {{
                navigator.serviceWorker.register('/service-worker.js')
                    .then(function(registration) {{
                        console.log('SW registered: ', registration);
                    }})
                    .catch(function(registrationError) {{
                        console.log('SW registration failed: ', registrationError);
                    }});
            }});
        }}
    </script>
"""
            
            # Head tag'ning ichiga meta-teglarni qo'shish
            if '</head>' in content:
                content = content.replace('</head>', f'{meta_tags}\n</head>')
            elif '<head>' in content:
                content = content.replace('<head>', f'<head>\n{meta_tags}')
            else:
                # Head tag mavjud emas, eng boshiga qo'shish
                content = f'<!DOCTYPE html>\n<html>\n<head>\n{meta_tags}\n</head>\n{content}'
            
            # Yangilangan kontentni yozish
            async with aiofiles.open(html_path, 'w', encoding='utf-8') as f:
                await f.write(content)
            
            logger.info(f"PWA meta-teglar qo'shildi: {html_path}")
            
        except Exception as e:
            logger.error(f"Meta-teglar qo'shish xatosi {html_path}: {str(e)}")

    async def _setup_update_system(self):
        """Update tizimini o'rnatish"""
        logger.info("🔄 Update tizimi o'rnatilmoqda...")
        
        update_manager_path = self.project_root / "update-manager.js"
        
        update_js = """
// PWA Update Manager
// Generated by PWA Manager

class UpdateManager {
    constructor() {
        this.updateAvailable = false;
        this.registration = null;
    }
    
    async init() {
        if ('serviceWorker' in navigator) {
            navigator.serviceWorker.addEventListener('controllerchange', () => {
                window.location.reload();
            });
            
            // Check for updates periodically
            this.startPeriodicCheck();
        }
    }
    
    async checkForUpdates() {
        if (!('serviceWorker' in navigator)) {
            return false;
        }
        
        try {
            const registration = await navigator.serviceWorker.getRegistration();
            if (registration) {
                await registration.update();
                return this.handleUpdateFound(registration);
            }
        } catch (error) {
            console.error('Error checking for updates:', error);
        }
        
        return false;
    }
    
    async handleUpdateFound(registration) {
        if (registration.waiting) {
            this.updateAvailable = true;
            this.registration = registration;
            
            // Show update notification
            this.showUpdateNotification();
            return true;
        }
        
        return false;
    }
    
    showUpdateNotification() {
        // Create update notification UI
        const notification = document.createElement('div');
        notification.className = 'pwa-update-notification';
        notification.innerHTML = `
            <div class="update-content">
                <h3>App yangilanishi mavjud</h3>
                <p>Yangi xususiyatlar va yaxshilanishlar yuklashga tayyor.</p>
                <div class="update-actions">
                    <button id="update-now" class="update-btn">Hoziroq yangilash</button>
                    <button id="update-later" class="update-btn secondary">Keyinroq</button>
                </div>
            </div>
        `;
        
        document.body.appendChild(notification);
        
        // Add event listeners
        document.getElementById('update-now').addEventListener('click', () => {
            this.applyUpdate();
        });
        
        document.getElementById('update-later').addEventListener('click', () => {
            notification.remove();
        });
    }
    
    async applyUpdate() {
        if (this.registration && this.registration.waiting) {
            this.registration.waiting.postMessage({type: 'SKIP_WAITING'});
        }
    }
    
    startPeriodicCheck() {
        // Check for updates every hour
        setInterval(() => {
            this.checkForUpdates();
        }, 3600000); // 1 hour
    }
}

// Initialize update manager
document.addEventListener('DOMContentLoaded', function() {
    const updateManager = new UpdateManager();
    updateManager.init();
    window.updateManager = updateManager;
});
"""
        
        async with aiofiles.open(update_manager_path, 'w', encoding='utf-8') as f:
            await f.write(update_js)
        
        logger.info(f"Update manager yaratildi: {update_manager_path}")

    async def _setup_installation_prompt(self):
        """Installation prompt o'rnatish"""
        logger.info("📱 Installation prompt o'rnatilmoqda...")
        
        install_prompt_path = self.project_root / "install-prompt.js"
        
        install_js = """
// PWA Installation Prompt Manager
// Generated by PWA Manager

class InstallPromptManager {
    constructor() {
        this.deferredPrompt = null;
        this.isInstalled = this.checkIfInstalled();
    }
    
    async init() {
        // Listen for the beforeinstallprompt event
        window.addEventListener('beforeinstallprompt', (e) => {
            e.preventDefault();
            this.deferredPrompt = e;
            this.showInstallPrompt();
        });
        
        // Listen for successful installation
        window.addEventListener('appinstalled', () => {
            this.hideInstallPrompt();
            this.isInstalled = true;
            console.log('PWA was installed');
        });
    }
    
    checkIfInstalled() {
        // Check if app is already installed
        if (window.matchMedia('(display-mode: standalone)').matches) {
            return true;
        }
        
        if ((window.navigator.standalone === true) || 
            (window.matchMedia('(display-mode: standalone)').matches)) {
            return true;
        }
        
        return false;
    }
    
    showInstallPrompt() {
        if (this.isInstalled || !this.deferredPrompt) {
            return;
        }
        
        // Create install banner or button
        const installBanner = document.createElement('div');
        installBanner.className = 'pwa-install-banner';
        installBanner.innerHTML = `
            <div class="install-content">
                <div class="install-icon">📱</div>
                <div class="install-text">
                    <h3>Ushbu ilovani o'rnatish</h3>
                    <p>Tezroq kirish va offline ishlatish uchun ilovani o'rnating</p>
                </div>
                <div class="install-actions">
                    <button id="install-app" class="install-btn">O'rnatish</button>
                    <button id="dismiss-install" class="install-btn secondary">Yopish</button>
                </div>
            </div>
        `;
        
        document.body.appendChild(installBanner);
        
        // Add event listeners
        document.getElementById('install-app').addEventListener('click', () => {
            this.promptInstall();
        });
        
        document.getElementById('dismiss-install').addEventListener('click', () => {
            this.hideInstallPrompt();
        });
    }
    
    hideInstallPrompt() {
        const banner = document.querySelector('.pwa-install-banner');
        if (banner) {
            banner.remove();
        }
    }
    
    async promptInstall() {
        if (!this.deferredPrompt) {
            return;
        }
        
        // Show the install prompt
        this.deferredPrompt.prompt();
        
        // Wait for the user to respond to the prompt
        const result = await this.deferredPrompt.userChoice;
        
        if (result.outcome === 'accepted') {
            console.log('User accepted the install prompt');
        } else {
            console.log('User dismissed the install prompt');
        }
        
        this.deferredPrompt = null;
        this.hideInstallPrompt();
    }
    
    async forceInstall() {
        // Alternative install method for browsers that don't support prompts
        if (this.isInstalled) {
            return;
        }
        
        // Show instructions for manual installation
        const installInstructions = document.createElement('div');
        installInstructions.className = 'pwa-install-instructions';
        installInstructions.innerHTML = `
            <div class="install-content">
                <h3>Ilovani qo'lda o'rnatish</h3>
                <p>Brauzeringiz menyusi orqali "Ushbu sahifani ilovaga qo'shish" yoki "Home screen ga qo'shish" tanlang.</p>
                <button class="install-btn" onclick="this.parentElement.parentElement.remove()">Tushundim</button>
            </div>
        `;
        
        document.body.appendChild(installInstructions);
    }
}

// Initialize install prompt manager
document.addEventListener('DOMContentLoaded', function() {
    const installManager = new InstallPromptManager();
    installManager.init();
    window.installPromptManager = installManager;
});
"""
        
        async with aiofiles.open(install_prompt_path, 'w', encoding='utf-8') as f:
            await f.write(install_js)
        
        logger.info(f"Install prompt manager yaratildi: {install_prompt_path}")

    async def _setup_network_detection(self):
        """Network detection o'rnatish"""
        logger.info("🌐 Network detection o'rnatilmoqda...")
        
        network_detector_path = self.project_root / "network-detector.js"
        
        network_js = """
// Network Detection Manager
// Generated by PWA Manager

class NetworkDetector {
    constructor() {
        this.isOnline = navigator.onLine;
        this.connection = navigator.connection || navigator.mozConnection || navigator.webkitConnection;
        this.listeners = [];
        
        this.init();
    }
    
    init() {
        // Listen for online/offline events
        window.addEventListener('online', () => this.handleOnline());
        window.addEventListener('offline', () => this.handleOffline());
        
        // Listen for connection changes (if supported)
        if (this.connection) {
            this.connection.addEventListener('change', () => this.handleConnectionChange());
        }
    }
    
    handleOnline() {
        this.isOnline = true;
        this.notifyListeners('online');
        console.log('Network: Online');
        
        // Trigger background sync if available
        if ('serviceWorker' in navigator && 'sync' in window.ServiceWorkerRegistration.prototype) {
            navigator.serviceWorker.ready.then(registration => {
                registration.sync.register('background-sync');
            });
        }
    }
    
    handleOffline() {
        this.isOnline = false;
        this.notifyListeners('offline');
        console.log('Network: Offline');
    }
    
    handleConnectionChange() {
        this.notifyListeners('connectionchange', {
            effectiveType: this.connection.effectiveType,
            downlink: this.connection.downlink,
            rtt: this.connection.rtt
        });
        console.log('Connection changed:', {
            effectiveType: this.connection.effectiveType,
            downlink: this.connection.downlink,
            rtt: this.connection.rtt
        });
    }
    
    on(event, callback) {
        this.listeners.push({event, callback});
    }
    
    notifyListeners(event, data = {}) {
        this.listeners.forEach(listener => {
            if (listener.event === event) {
                listener.callback(data);
            }
        });
    }
    
    getNetworkInfo() {
        return {
            isOnline: this.isOnline,
            connection: this.connection ? {
                effectiveType: this.connection.effectiveType,
                downlink: this.connection.downlink,
                rtt: this.connection.rtt,
                saveData: this.connection.saveData
            } : null
        };
    }
    
    showConnectionStatus() {
        // Create network status indicator
        const statusIndicator = document.createElement('div');
        statusIndicator.className = 'network-status-indicator';
        statusIndicator.innerHTML = `
            <span class="status-icon ${this.isOnline ? 'online' : 'offline'}">
                ${this.isOnline ? '🌐' : '📵'}
            </span>
            <span class="status-text">
                ${this.isOnline ? 'Online' : 'Offline'}
            </span>
        `;
        
        // Add to page
        document.body.appendChild(statusIndicator);
        
        // Update on network changes
        this.on('online', () => this.updateStatusIndicator(statusIndicator, true));
        this.on('offline', () => this.updateStatusIndicator(statusIndicator, false));
    }
    
    updateStatusIndicator(indicator, isOnline) {
        const icon = indicator.querySelector('.status-icon');
        const text = indicator.querySelector('.status-text');
        
        icon.textContent = isOnline ? '🌐' : '📵';
        icon.className = `status-icon ${isOnline ? 'online' : 'offline'}`;
        text.textContent = isOnline ? 'Online' : 'Offline';
        
        // Show temporary message
        const message = document.createElement('div');
        message.className = 'network-message';
        message.textContent = isOnline ? 'Internet aloqasi tiklandi' : 'Internet aloqasi uzilgan';
        document.body.appendChild(message);
        
        setTimeout(() => message.remove(), 3000);
    }
}

// Initialize network detector
document.addEventListener('DOMContentLoaded', function() {
    const networkDetector = new NetworkDetector();
    window.networkDetector = networkDetector;
    
    // Show status indicator
    networkDetector.showConnectionStatus();
});
"""
        
        async with aiofiles.open(network_detector_path, 'w', encoding='utf-8') as f:
            await f.write(network_js)
        
        logger.info(f"Network detector yaratildi: {network_detector_path}")

    async def _validate_pwa(self):
        """PWA validatsiya qilish"""
        logger.info("✅ PWA validatsiya qilinmoqda...")
        
        validation_results = {
            "service_worker": await self._validate_service_worker(),
            "manifest": await self._validate_manifest(),
            "icons": await self._validate_icons(),
            "https": self._validate_https(),
            "responsive": await self._validate_responsive(),
            "offline": await self._validate_offline_capability()
        }
        
        # Validation hisoboti
        report_path = self.pwa_dir / "validation_report.json"
        async with aiofiles.open(report_path, 'w', encoding='utf-8') as f:
            await f.write(json.dumps(validation_results, indent=2, ensure_ascii=False))
        
        logger.info(f"PWA validation hisoboti: {report_path}")

    async def _validate_service_worker(self) -> Dict:
        """Service Worker validatsiya"""
        sw_path = self.project_root / "service-worker.js"
        return {
            "exists": sw_path.exists(),
            "size": sw_path.stat().st_size if sw_path.exists() else 0,
            "readable": sw_path.exists() and sw_path.stat().st_size > 0
        }

    async def _validate_manifest(self) -> Dict:
        """Manifest validatsiya"""
        manifest_path = self.project_root / "manifest.json"
        
        if not manifest_path.exists():
            return {"exists": False}
        
        try:
            async with aiofiles.open(manifest_path, 'r', encoding='utf-8') as f:
                content = await f.read()
                manifest = json.loads(content)
            
            required_fields = ["name", "short_name", "icons", "start_url", "display"]
            missing_fields = [field for field in required_fields if field not in manifest]
            
            return {
                "exists": True,
                "valid_json": True,
                "required_fields_present": len(missing_fields) == 0,
                "missing_fields": missing_fields,
                "fields_count": len(manifest)
            }
        except Exception as e:
            return {
                "exists": True,
                "valid_json": False,
                "error": str(e)
            }

    async def _validate_icons(self) -> Dict:
        """Icon validatsiya"""
        icon_sizes = [72, 96, 128, 144, 152, 192, 384, 512]
        existing_icons = []
        missing_icons = []
        
        for size in icon_sizes:
            icon_path = self.project_root / f"icon-{size}x{size}.png"
            if icon_path.exists():
                existing_icons.append(size)
            else:
                missing_icons.append(size)
        
        return {
            "existing_icons": existing_icons,
            "missing_icons": missing_icons,
            "coverage_percentage": len(existing_icons) / len(icon_sizes) * 100
        }

    def _validate_https(self) -> Dict:
        """HTTPS validatsiya"""
        return {
            "https_required": True,
            "localhost_allowed": True,
            "current_protocol": "https" if os.environ.get('HTTPS', '').lower() == 'true' else "http"
        }

    async def _validate_responsive(self) -> Dict:
        """Responsive design validatsiya"""
        index_files = list(self.project_root.glob("**/index.html"))
        
        has_viewport = False
        for index_path in index_files:
            try:
                async with aiofiles.open(index_path, 'r', encoding='utf-8') as f:
                    content = await f.read()
                    if 'viewport' in content:
                        has_viewport = True
                        break
            except:
                pass
        
        return {
            "viewport_meta_present": has_viewport,
            "responsive_required": True
        }

    async def _validate_offline_capability(self) -> Dict:
        """Offline capability validatsiya"""
        offline_path = self.project_root / self.config.offline_page.lstrip('/')
        return {
            "offline_page_exists": offline_path.exists(),
            "service_worker_configured": True,
            "cache_strategy_configured": True
        }

    async def _generate_pwa_report(self):
        """PWA hisoboti yaratish"""
        logger.info("📊 PWA hisoboti yaratilmoqda...")
        
        report = {
            "pwa_info": {
                "app_name": self.config.app_name,
                "short_name": self.config.short_name,
                "version": self.config.version,
                "setup_date": datetime.now().isoformat()
            },
            "features": {
                "service_worker": True,
                "web_manifest": True,
                "push_notifications": self.config.enable_push,
                "background_sync": self.config.enable_background_sync,
                "offline_capability": True,
                "installable": True
            },
            "file_structure": {
                "service_worker": str(self.project_root / "service-worker.js"),
                "manifest": str(self.project_root / "manifest.json"),
                "offline_page": str(self.project_root / self.config.offline_page.lstrip('/')),
                "pwa_assets_dir": str(self.pwa_dir)
            },
            "optimization_status": {
                "cache_configured": True,
                "update_system": True,
                "install_prompt": True,
                "network_detection": True
            },
            "recommendations": [
                "PWA PWA Audit tool bilan sinab ko'ring",
                "App Store distribution uchun native wrapper qo'shing",
                "Performance monitoring qo'shing",
                "User engagement analytics qo'shing",
                "App rating va review system qo'shing"
            ]
        }
        
        # Hisobotni saqlash
        report_path = self.pwa_dir / "pwa_setup_report.json"
        async with aiofiles.open(report_path, 'w', encoding='utf-8') as f:
            await f.write(json.dumps(report, indent=2, ensure_ascii=False))
        
        logger.info(f"PWA setup hisoboti saqlandi: {report_path}")

    def _get_created_files(self) -> List[str]:
        """Yaratilgan fayllar ro'yxati"""
        files = [
            "service-worker.js",
            "manifest.json",
            self.config.offline_page.lstrip('/'),
            "push-notification-manager.js",
            "background-sync.js",
            "update-manager.js",
            "install-prompt.js",
            "network-detector.js"
        ]
        
        return [str(self.project_root / f) for f in files if (self.project_root / f).exists()]

    def get_pwa_status(self) -> Dict:
        """PWA holatini olish"""
        sw_exists = (self.project_root / "service-worker.js").exists()
        manifest_exists = (self.project_root / "manifest.json").exists()
        offline_exists = (self.project_root / self.config.offline_page.lstrip('/')).exists()
        
        return {
            "service_worker_configured": sw_exists,
            "manifest_configured": manifest_exists,
            "offline_page_configured": offline_exists,
            "pwa_score": sum([sw_exists, manifest_exists, offline_exists]) / 3 * 100
        }

# CLI interface
async def main():
    """Asosiy funksiya"""
    import argparse
    
    parser = argparse.ArgumentParser(description="PWA Manager - Progressive Web App Manager")
    parser.add_argument("--project-root", required=True, help="Loyiha ildiz papka")
    parser.add_argument("--app-name", required=True, help="Ilova nomi")
    parser.add_argument("--short-name", required=True, help="Qisqa nom")
    parser.add_argument("--start-url", default="/", help="Boshlang'ich URL")
    parser.add_argument("--theme-color", default="#000000", help="Mavzu rangi")
    parser.add_argument("--background-color", default="#ffffff", help="Orqa fon rangi")
    parser.add_argument("--enable-push", action="store_true", help="Push notification yoqish")
    parser.add_argument("--enable-background-sync", action="store_true", help="Background sync yoqish")
    parser.add_argument("--output", help="Hisobot fayl yo'li")
    
    args = parser.parse_args()
    
    # PWA config yaratish
    config = PWAConfig(
        app_name=args.app_name,
        short_name=args.short_name,
        start_url=args.start_url,
        theme_color=args.theme_color,
        background_color=args.background_color,
        enable_push=args.enable_push,
        enable_background_sync=args.enable_background_sync
    )
    
    # PWA Manager yaratish
    manager = PWAManager(args.project_root, config)
    
    # PWA setup o'tkazish
    try:
        results = await manager.setup_pwa()
        
        # Natijani ko'rsatish
        print("\n📱 PWA MANAGER NATIJASI:")
        print("=" * 50)
        print(f"App nomi: {config.app_name}")
        print(f"Service Worker: {'✅' if results['status'] == 'success' else '❌'}")
        print(f"Web Manifest: ✅")
        print(f"Offline capability: ✅")
        
        if args.output:
            with open(args.output, 'w', encoding='utf-8') as f:
                json.dump(results, f, indent=2, ensure_ascii=False)
            print(f"Hisobot saqlandi: {args.output}")
        
        print("\n🎉 PWA muvaffaqiyatli sozlangan!")
        print("Keyingi qadamlar:")
        print("1. HTTPS yoqish (PWA uchun majburiy)")
        print("2. PWA Audit tool bilan test qilish")
        print("3. App Store submission")
        
    except Exception as e:
        logger.error(f"PWA setup xatosi: {str(e)}")
        return 1
    
    return 0

if __name__ == "__main__":
    asyncio.run(main())